### PR TITLE
iOS 9.2.1 Compatibility

### PR DESCRIPTION
**Pull request by JBA474**
Thanks to Kristian @trenskow for a fabulous application and having the stones to open source it for everyone to learn and benefit from. Most devs I know would have walked away when Apple screwed them.
Merged submodule for libairfloat (sorry Kristian I find submodules annoying to work with, I hope you don't mind), updated libz.tbd, disabled bitcode, enabled build only active architecture, strip debug symbols. Works on non-jailbroken iPhone iOS 6s Plus 9.2.1 as the AirPlay target of a 4th gen non-jailbroken Apple TV tvOS 9.1.1. This builds and deploys successfully with a free Apple ID, Apple Developer account not needed for personal devices. You must use at least iOS 9 and Xcode 7.
Did not change build target.
Changed NSArray in AirFloatAppDelegate.m to fix issue #50 - Custom Name Does Not Persist credit to @yfliao.
Changed AVAudioSession to work around crash when switching songs, I believe this resolves issue #38.
Added hack for return iOSDeviceID to allow multiple instances on Airflow on the same network and work around MAC address no longer available in app sandbox credit to @ataibarkai.
Fixed a couple other memory management bugs in settings.c, web request.c and webserver.c, including removing redundant socket_destroy. I believe this was causing the crash when switching from one Netflix episode to the next credit to @faisalmemon.
Changed target name for libairfloat from airfloat to libairfloat.

All ready to put on the App Store, just kidding :)

I believe all of these issues should be retested, verified and closed out after this change is merged.
libAirFloat Issue #6 Memory Management Bugs (at least the specific changes brought up in the issue document)
AirFloat Issue #20 Sound Mutes When Switching Apps Or Turning Off The Screen (I tested and it's working)
AirFloat Issue #23 Background Processing (entitlement change allows this, tested working)
AirFloat Issue #37 Multiple Instances Of AirFloat In One Network (this was broken with app sandboxing, put in work around)
AirFloat Issue #38 AirFloat Connection Silently Fails After Muting Sound For A Few Seconds (I tested and it's working)
AirFloat Issue #45 Run Without Apple Dev Cert (I tested and it's working)
AirFloat Issue #48 Crashes When Getting Audio From Apple TV  (I've got an old AppleTV but I only tested against the most recent 4th Gen)
AirFloat Issue #50 Custom Name Does Not Persist (Put in work around, tested and working)
AirFloat Issue #51 Cannot Build On Latest Xcode (I tested and it's working)

### CODE REVIEW

**Comment by trenskow** [comment]
Hi @JBA474 
This is perfect! I have no problem with libairfloat being merged into AirFloat. I'll merge this later today. :+1:

**Comment by JBA474** [comment]
I was seriously nervous you would think I was a real jerk for undoing the split you made.  The separate xcode project for the libairfloat library makes total sense to me and I'm 95% sure I didn't mess anything up.  If you could double check the history looks correct on the merged in libairfloat I would appreciate it so you (we) don't loose any of the history when merging my pull request.  If you see any problems I'll happily fix it.

Thanks again for all the work you do, this is a great project and I had fun contributing something.

**Comment by trenskow** [comment]
It's super alright. I am more than happy about the contributions you make! :)
I originally split it because I thought I wanted to port libairfloat to other platforms - but since that has never happened, it really makes no sense having it split. So I'm all for it. Plus people are having a hard time figuring, that they need to fork two to make contributions - which is really a pain for a lot I guess.
Thanks for the good work! Keep 'em coming! :+1: :)

**Comment by trenskow** [comment]
Why haven't you added yourself to the list of contributors?

**Comment by JBA474** [comment]
Please add me, it would be an honor.  I didn't add myself because it was in my repo and I didn't think about it when I created the pr.  Rookie mistake, forgive me please.

**Comment by vrudikov** [comment]
> I wanted to port libairfloat to other platforms
Maybe it's a good idea and multi-platform libairfloat should takes it's own place at https://github.com/trenskow/libairfloat

**Comment by trenskow** [comment]
@vrudikov I agree. It would be the best scenario, but as of now there is no prospect of it getting ported to other platforms. I have, though, tried to structure it, so it would be relatively easy. For Linux it needs to get another audio_output.c implementation for Linux APIs. The same goes for Windows except there stuff like threading needs to be ported too.

**Pull request merged**
